name: CI

on:
  push:
    branches: [main]
    tags:
      - '*.*.*'

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint & check code style
        run: npm run lint:check && npm run prettier:check

      - name: Run tests
        run: npm run test

      - name: Prepare environment for a new release
        if: github.ref_type == 'tag'
        run: |
          sudo apt update
          sudo apt install -y curl tar
          bash install_rcodesign.sh
          npm i -g pkg

      - name: Prepare files for a new release
        if: github.ref_type == 'tag'
        run: |
          npm run compile
          npm run bake
          cd dist
          find . -maxdepth 1 -type f ! -name "*.js" | while IFS= read -r file; do
            rcodesign sign "$file"
            chmod +x "$file"
            zip -0 "${file}.zip" "$file"
            rm "$file"
          done

      - name: Create a new release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: |
            dist/mshrinker-*
